#!/bin/sh
# This file is generated by Flutter during local builds and should not be
# checked into version control.
#
# The generated environment exports were removed from the repository because
# they can contain machine-specific absolute paths and other local build data.
# Regenerate this file by running the appropriate Flutter build command.
